[project]
name = "git-org-metrics"
version = "0.1.0"
description = "Experiment to visualize Git repo metrics in static page."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.5.3",
]

[dependency-groups]
dev = [
    "pip-audit>=2.10.0",
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "ruff>=0.16.1",
    "sqlfluff>=4.2.2",
    "ty>=0.0.66",
]

[tool.uv]
exclude-newer = "7 days"
